# Generated by Django 4.1.5 on 2023-05-21 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cuenta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barista',
            name='name',
        ),
        migrations.RemoveField(
            model_name='barista',
            name='password',
        ),
        migrations.RemoveField(
            model_name='barista',
            name='username',
        ),
        migrations.AddField(
            model_name='barista',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
