# Generated by Django 4.1.5 on 2023-05-31 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0002_remove_barista_name_remove_barista_password_and_more'),
        ('Productos', '0002_eventos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventos',
            old_name='nome',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='eventos',
            name='barista',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cuenta.barista'),
            preserve_default=False,
        ),
    ]
