# Generated by Django 4.1.5 on 2023-06-12 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0004_reservas_pedidos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservas',
            name='num_reservaciones',
        ),
    ]
